In [3]:
import numpy as np


In [4]:
# Eye()---> It will  create an array in which digonal positional element are 1 and rest all are 0

In [6]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# Diag()----> it will set our custm values on digonal postion

In [9]:
a=np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [11]:
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [12]:
# Random Module --->
# (A) Randint()---> it will create random numbers in a given range
# syntax np.random.randint(min_range,max_range,total_range)

In [14]:
a=np.random.randint(1,10,3)
a

array([3, 7, 8])

In [15]:
# B Rand()--> it will create random numbers in range 0-1/


In [19]:
a=np.random.rand(5)
a

array([0.95426377, 0.46895151, 0.96323036, 0.11264312, 0.02062924])

In [20]:
#(c) Seed()---> it will fix our random genrated data

In [23]:
np.random.seed(3)
a=np.random.randint(1,10,3)
a

array([9, 4, 9])

In [24]:
# View vs copy

# view means modififcation in original data and copy mens  change in duplicate data will not reflect

In [25]:
a=np.array([10,20,30,40,50,60,70,80])

In [27]:
a[3:6]=0

In [29]:
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [33]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
b

array([0, 0, 0])

In [35]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [36]:
# operation  on array

In [37]:
# (1) arange()---> It will works as for loop in numpy.

In [39]:
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [43]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [44]:
b=a%2==0

In [46]:
a[b]

array([ 2,  4,  6,  8, 10, 12, 14])

In [47]:
# Reshaping condition
#n(rows)*n(columns)=n(total_elements)

In [48]:
# total element=12
# 1*12,12*1
#2*6,6*2
#3*4,4*3

In [49]:
a=np.random.randint(1,50,12)
a

array([ 9,  1, 22, 20, 11, 44, 42, 11, 22, 39, 33, 21])

In [50]:
a.reshape(2,6)

array([[ 9,  1, 22, 20, 11, 44],
       [42, 11, 22, 39, 33, 21]])

In [53]:
a.reshape(3,4)


array([[ 9,  1, 22, 20],
       [11, 44, 42, 11],
       [22, 39, 33, 21]])

In [55]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [58]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [60]:
a+b

array([[ 6,  8],
       [10, 12]])

In [63]:
a-b

array([[-4, -4],
       [-4, -4]])

In [65]:
a*b   # not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [67]:
a.dot(b)  # matrix multiplication

array([[19, 22],
       [43, 50]])

In [68]:
a

array([[1, 2],
       [3, 4]])