In [1]:
import numpy as np

In [3]:
a=np.arange(1,5) reshape(2,2)
a

array([1, 2, 3, 4])

In [5]:
a**2

array([ 1,  4,  9, 16])

In [7]:
a**3

array([ 1,  8, 27, 64])

In [9]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [10]:
#linspace()--->  It will return same gap values in given range

In [12]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
# Unique() ---->  It will retrun 3 arrays
# arr ---> return original values of array
# return_index= True ---> return index value of unique numbers
# return_counts= True --> It will retrun total Frequency of each unique value

In [15]:
a=np.array([1,2,3,2,2,2,3,2,4,5])
a

array([1, 2, 3, 2, 2, 2, 3, 2, 4, 5])

In [17]:
np.unique(a, return_index=True , return_counts=True)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 8, 9]), array([1, 5, 2, 1, 1]))

In [18]:
#hstack()  and vstack()
#hstack()---> It will add 2 or more arrays in horizontally.
#vstack()---> It will add 2 or more arrays in Vertically.



In [28]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(5,9).reshape(2,2)
c=np.arange(9,13).reshape(2,2)

In [27]:
np.hstack((a,b,c))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [30]:
np.vstack((a,b,c))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
# array (30,80) total element 36-- reshape(2,18,4,9)(6*6)


In [39]:
np.random.seed(3)
a=np.random.randint(30,80,36).reshape(2,18)
b=np.random.randint(30,80,36).reshape(4,9)
c=np.random.randint(30,80,36).reshape(6,6)




In [40]:
print(a,b,c)

[[72 54 33 38 30 51 49 40 73 71 40 51 68 62 50 74 59 69]
 [44 56 47 56 52 32 32 31 56 35 70 76 63 59 72 54 37 73]] [[63 45 78 67 50 60 79 51 44]
 [58 30 30 71 48 67 37 67 76]
 [63 79 31 51 40 73 66 65 57]
 [46 46 62 46 48 41 62 61 43]] [[67 60 78 63 79 32]
 [58 66 56 70 74 78]
 [40 78 66 57 79 51]
 [79 70 69 59 62 78]
 [39 63 77 54 41 50]
 [40 78 46 42 34 74]]


In [45]:
# array [5,10],[11,15]--> combined horizontally

a=np.arange(6,11)
b=np.arange(11,15)

np.hstack((a,b))

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
a,b

(array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14]))