In [1]:
# Numpy-  This is an open -source library of python and this is used for scientific calculation
# list is hetrogeneous data type andnumpy is homogenuos data type.

In [2]:
a=[1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [34]:
a=np.array([1,2,3])
a*3


array([3, 6, 9])

In [4]:
import numpy as np


In [5]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [7]:
print(type(a))
print(type(b))
b

<class 'list'>
<class 'numpy.ndarray'>


array([1, 2, 3])

In [10]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#Row =3 ,r_1=[1,2,3],r_2=[4,5,6],r_3=[7,8,9]
#column =3 , c_1=[1,4,7],c_2=[2,5,8],c_3=[3,6,9]


In [13]:
print("total shape:",b.shape)   # shape =(row,column)
print("total element",b.size)   # size= row*column
print("Total Dimensions",b.ndim)

total shape: (3, 3)
total element 9
Total Dimensions 2


In [14]:
# pre-built function of Numpy

In [15]:
# Zero()-- It will create an array in which all the values will be 0 in either
# one Dimensional or multi-Dimensional.

In [17]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [21]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
#2.Ones()--> It will return an array in which all the values are 1 in either
# one Dimension or multi-dimension


In [24]:
a=np.ones((3))
a

array([1., 1., 1.])

In [26]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr=np.ones((5,6))
arr


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
print("Total Dimen",arr.ndim)
print("Total Element",arr.size)

Total Dimen 2
Total Element 30
